//
// Created by jens on 31/03/24.
//

#include <iostream>
#include "toplevel.h"
#include "iobase.h"

void toplevel::visit(alien a)
{
    auto cb = [&a](pathpoint p)
    {
        a.point(*p);
    };
    a.begin_world();
    try {
        for(;;) {
            auto m = g_.find_polygon();
            a.begin_poly();
            trail_walk w(w_, cb);
            auto [p, q] = w.walk(m.begin(), m.end());
            if(p != q) {
                std::cerr << "Non-closed polygon; can't happen\n";
            }
            a.end_poly();
        }
    }
    catch(graph::AllDone)
    {}
    // TODO: run through unused paths (these have to be generated by the graph object)
    a.end_world();
}


iobase *toplevel::make_io(toplevel::io_type_t) {
    return new ioxfig(w_, g_);
}
